# Generated by Django 3.2.25 on 2026-08-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='attendance',
            field=models.BooleanField(default=False),
        ),
    ]
