# Generated by Django 3.2.25 on 2026-09-28 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_registration_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='available_seats',
        ),
    ]
